services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/testYiiProject
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www/testYiiProject
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mike
      MYSQL_DATABASE: testYiiProject_db
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql